spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/controlai}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false
    baseline-on-migrate: true

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.jdbc: DEBUG

aws:
  region: ${AWS_REGION:us-east-2}
  sqs:
    endpoint: ${AWS_SQS_ENDPOINT:}
    purchase-from-notification-queue-url: ${AWS_SQS_PURCHASE_FROM_NOTIFICATION_QUEUE_URL:https://sqs.us-east-2.amazonaws.com/111710312790/purchase-from-notification}
