-- V18__create_budget_incomes_table.sql
CREATE TABLE budget_incomes (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    budget_id BIGINT NOT NULL,
    label VARCHAR(100) NOT NULL,
    amount DECIMAL(19,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_binc_budget FOREIGN KEY (budget_id) REFERENCES budgets (id) ON DELETE CASCADE
);
